### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by avlkv** [S3-Platform-Inc/s3p-plugin-parser-visa#1]
Та же ошибка вроде бы, что и у PWC
`selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 39.314`
Весь лог тестов приложил.
[visa_log.txt](https://github.com/user-attachments/files/17842212/visa_log.txt)

**Comment by CuberHuber** [comment]
Проблема заключалась в том, что в логике парсера была допущена ошибка.
метод  `_find` возвращает определенную ошибку, если нужно закончить работу парсера, но это не было учтено при написании метода `_parse_archive_page`
